language: python
python:
  - "3.6"
  - "2.7"

install:
  - sed -i "s/WeaveLib.git/WeaveLib.git@$TRAVIS_BRANCH/g" requirements.txt
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install -r dev-requirements.txt

script:
  - coverage run --source weaveenv -m py.test

after_success:
  - coveralls
